version: '3'
services:
  tx:
    # need to start using healthcheck to ensure cassandra is up. sleep could be adequate for now tho
    container_name: tx_container
    depends_on:
      - cassandra
    build: ./tx
    volumes:
      - ./tx:/go/src/app
      - ./db/:/db
  web:
    container_name: web_container
    ports: 
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - tx
    build: ./web
    volumes:
      - ./web:/go/src/app
  cassandra:
    container_name: cassandra_container
    image: "cassandra"
    volumes:
      - ./db:/db
