version: '3'
services:
  web:
    # need to start using healthcheck to ensure cassandra is up. sleep could be adequate for now tho
    container_name: web
    ports:
      - "8082:8082" # port that is exposed for the web server
    build: ./server
    volumes:
      - ./server:/go/src/app
    environment:
      ROLE: web
      QUOTE_SERVER_URL: "quoteserve:4448"
      DB_HOST: "db"
      DB_PORT: "5432"
      REDIS_URL: "redis:6379"
    networks:
      default:
        aliases:
          - web

  job:
    container_name: job
    build: ./server
    volumes:
      - ./server:/go/src/app
    networks:
      default:
        aliases:
          - job
    environment:
      ROLE: job
      QUOTE_SERVER_URL: "quoteserve:4448"
      DB_HOST: "db"
      DB_PORT: "5432"
      REDIS_URL: "redis:6379"

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: badgerboi
      POSTGRES_USER: badgerboi
      POSTGRES_DB: badgerboi
    command: "-c max_connections=1000"

  db_proxy:
    depends_on:
      - db
    container_name: db_proxy
    image: brainsam/pgbouncer:latest
    restart: always
    environment:
      DB_HOST: db
      DB_USER: badgerboi
      DB_PASSWORD: badgerboi
      MAX_DB_CONNECTIONS: 1000

  quote:
    container_name: quote
    ports:
      - "4448:4448"
    build: ./quoteServer
    volumes:
      - ./quoteServer:/go/src/app
    networks:
      default:
        aliases:
          - quoteserve

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  workload:
    container_name: workload
    build: ./workloadGen
    volumes:
      - ./workloadGen:/go/src/app
    environment:
      WEB_URL: "web:8082"
