version: '3'
services:
  web:
    # need to start using healthcheck to ensure cassandra is up. sleep could be adequate for now tho
    container_name: web_container
    ports:
      - "8082:8082" # port that is exposed for the web server
    depends_on:
      - db
      - redis
      - quote
    build: ./server
    volumes:
      - ./server:/go/src/app
    environment:
      ROLE: web
      QUOTE_SERVER_URL: "quoteserve:4448"
    networks:
      default:
        aliases:
          - web

  job:
    container_name: job_container
    depends_on:
      - db
      - redis
      - quote
    build: ./server
    volumes:
      - ./server:/go/src/app
    networks:
      default:
        aliases:
          - job
    environment:
      ROLE: job
      QUOTE_SERVER_URL: "quoteserve:4448"

  db:
    container_name: db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: badgerboi
      POSTGRES_USER: badgerboi
      POSTGRES_DB: badgerboi
    command: "-c max_connections=400"

  quote:
    container_name: quote_container
    ports:
      - "4448:4448"
    build: ./quoteServer
    volumes:
      - ./quoteServer:/go/src/app
    networks:
      default:
        aliases:
          - quoteserve

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  workload:
    container_name: workload
    build: ./workloadGen
    volumes:
      - ./workloadGen:/go/src/app
