version: '3'
services:
  tx:
    # need to start using healthcheck to ensure cassandra is up. sleep could be adequate for now tho
    container_name: tx_container
    ports:
      - "8082:8082"
    depends_on:
      - db
    build: ./tx
    volumes:
      - ./tx:/go/src/app
      - ./db/:/db
    networks:
      default:
        aliases:
          - tx
  web:
    container_name: web_container
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - tx
    build: ./web
    volumes:
      - ./web:/go/src/app
    networks:
      default:
        aliases:
          - web
  db:
    container_name: db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: badgerboi
      POSTGRES_USER: badgerboi
      POSTGRES_DB: badgerboi
  quote:
    container_name: quote_container
    ports:
      - "3333:3333"
    build: ./quoteServer
    volumes:
      - ./quoteServer:/go/src/app
    networks:
      default:
        aliases:
          - quoteServer

