version: '3'
services:
  web:
    # need to start using healthcheck to ensure cassandra is up. sleep could be adequate for now tho
    container_name: web_container
    ports:
      - "8082:8082" # port that is exposed for the web server
    depends_on:
      - db
    build: ./server
    volumes:
      - ./server:/go/src/app
      - ./db/:/db
    environment:
      ROLE: web
    networks:
      default:
        aliases:
          - web
  job:
    container_name: job_container
    depends_on:
      - db
    build: ./server
    volumes:
      - ./server:/go/src/app
    networks:
      default:
        aliases:
          - job
    environment:
      ROLE: job
  db:
    container_name: db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: badgerboi
      POSTGRES_USER: badgerboi
      POSTGRES_DB: badgerboi

  quote:
    container_name: quote_container
    ports:
      - "3333:3333"
    build: ./quoteServer
    volumes:
      - ./quoteServer:/go/src/app
    networks:
      default:
        aliases:
          - quoteServer

