version: '3'
services:
  web:
    # need to start using healthcheck to ensure cassandra is up. sleep could be adequate for now tho
    container_name: web
    ports:
      - "8082:8082" # port that is exposed for the web server
    depends_on:
      - db
    build: ./server
    volumes:
      - ./server:/go/src/app
    environment:
      ROLE: web
      QUOTE_SERVER_URL: "quoteserve:4448"
    networks:
      default:
        aliases:
          - web
  job:
    container_name: job
    depends_on:
      - db
    build: ./server
    volumes:
      - ./server:/go/src/app
    networks:
      default:
        aliases:
          - job
    environment:
      ROLE: job
      QUOTE_SERVER_URL: "quoteserve:4448"
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: badgerboi
      POSTGRES_USER: badgerboi
      POSTGRES_DB: badgerboi
    command: "-c max_connections=400"

  quote:
    container_name: quote
    ports:
      - "4448:4448"
    build: ./quoteServer
    volumes:
      - ./quoteServer:/go/src/app
    networks:
      default:
        aliases:
          - quoteserve
  workload:
    container_name: workload
    build: ./workloadGen
    volumes:
      - ./workloadGen:/go/src/app
