#!/bin/bash
HOST=cassandra
KEYSPACE=badgerboi
PORT=9042

COMMAND=$1
BASE_CMD="docker exec -it tx_container journey \
      --url cassandra://${HOST}:${PORT}/${KEYSPACE}?protocol=4&consistency=all&disable_init_host_lookup \
      --path /db/migrations migrate"

# pass the other args through to the script
CMD="${BASE_CMD} $@"
exec $CMD
